In [6]:
import numpy as np

a1 = np.array([1,2,3,4,5,6,7]) #,가 없음
print(a1)

[1 2 3 4 5 6 7]


In [8]:
a2 = np.array([ [1,2,3],[4,5,6]])
print(a2)

a3 = np.array([[ [1,2],[3,4] ] ,[[5,6 ],[7,8]] ])
print(a3)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
print(a2.shape) # 배열 행,열
print(a2.ndim) # 차원
print(a2.dtype) #자료형
print(a2.itemsize) # 바이트 단위
print(a2.size) # 전체 요소 개수 2 * 3

(2, 3)
2
int64
8
6


In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# list 에서 배열 접근을 위해서는 a[1][2]
print(arr[0,2])
row = [0,2]
cols = [2,2]
print(arr[row,cols])

3
[3 9]


In [26]:
arr = np.array([10,20,30,40,50])
print(arr[arr > 20])
print(arr[arr % 20 == 0])
arr[arr > 20] = 0
print(arr)
lists = [1,2]
print(arr[lists])

[30 40 50]
[20 40]
[10 20  0  0  0]
[20  0]


In [35]:
zero = np.zeros((4,4))
print(zero)
print()
ones = np.ones((4,4))
print(ones)
print()
ranges = np.arange(1,20,2) # 증가 간격이 명확할 때
print(ranges)
print()
linspaces = np.linspace(0 , 2 ,10) # 지정된 구간을 일정한 값의 개수가 필요할 때 
print(linspaces)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[ 1  3  5  7  9 11 13 15 17 19]

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped = np.reshape(arr,(3,4))
print(reshaped)
print()
resized = np.resize(arr,(6,6))
print(resized)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [61]:
# a = np.array([1,2,3])
# b = np.array([4,5,6])

# print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)

# arr1 = np.array([1,5,7,12,49,81,64])
# print(np.sqrt(arr1))
# print()
# print(np.exp(arr1))
# print()
# print(np.log(arr1))
# print()

angles = np.array([0,np.pi/6, np.pi/4,np.pi/3,np.pi/2])
print(np.sin(angles))
print()
print(np.cos(angles))
print()
print(np.tan(angles))
print()
print(np.sinh(angles))

[0.         0.5        0.70710678 0.8660254  1.        ]

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]

[0.         0.54785347 0.86867096 1.24936705 2.3012989 ]


In [84]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.hstack((a,b)))
print(np.vstack((a,b)))
print( np.column_stack((a,b))) # 열기준 합치기
print()

a = np.array([[1,2,3], [4,5,6]])
print(np.hsplit(a,3))
print(np.vsplit(a,2))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [87]:
a = np.array([1,2,3,4,5])
num = 10
print(num + a)

a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
print(a+b)

[11 12 13 14 15]
[[11 22 33]
 [14 25 36]]


In [203]:
from bs4 import BeautifulSoup
import requests

html_url="https://www.koreabaseball.com/Record/TeamRank/TeamRankDaily.aspx"
res = requests.get(html_url)
soup = BeautifulSoup(res.text, 'html.parser')

kbo_data = [i.text for i in soup.select( "#cphContents_cphContents_cphContents_udpRecord >table td")]
lists = [0,1,3,4,5,6]
kbo_data = [value for idx, value in enumerate(kbo_data) if idx%12 in lists][:60]
kbo_ranks = np.array(kbo_data).reshape((10,6))
head = np.array(["순위","팀","승","무","패","승률"])
result = np.vstack([head,kbo_ranks])

with open("rank.txt","w",encoding="utf-8") as file:
    file.write("=========================KBO 순위=========================\n")
    for row in range(len(result)):
        for col in range(result.shape[1]):
            file.write(f"{result[row][col]:<5}\t")
        file.write("\n")

with open("rank.txt",'r',encoding="utf-8") as file:
    data = file.read()
    print(data)
    

=============KBO 순위=============
순위   	팀    	승    	무    	패    	승률   	
1    	KIA  	87   	55   	2    	0.613	
2    	삼성   	78   	64   	2    	0.549	
3    	LG   	76   	66   	2    	0.535	
4    	두산   	74   	68   	2    	0.521	
5    	KT   	72   	70   	2    	0.507	
6    	SSG  	72   	70   	2    	0.507	
7    	롯데   	66   	74   	4    	0.471	
8    	한화   	66   	76   	2    	0.465	
9    	NC   	61   	81   	2    	0.430	
10   	키움   	58   	86   	0    	0.403	



In [215]:
from bs4 import BeautifulSoup
import requests

html_url="https://www.koreabaseball.com/Record/TeamRank/TeamRankDaily.aspx"
res = requests.get(html_url)
soup = BeautifulSoup(res.text, 'html.parser')

data = soup.find( "table", attrs={"class":"tData"})
values = data.find_all("tr")[1:]

lists = []
for value in values:
    tds = value.find_all("td")
    tds = [i.text.strip() for i in tds]

    lists.append([tds[0], tds[1],tds[3],tds[4],tds[5],tds[6]])


array =np.array(lists)
#print(array)

file_name = "rank2.txt"
header = "순위\t팀\t승\t무\t패\t승률"
with open(file_name,"w",encoding="utf-8") as file:
    #헤더 쓰기
    file.write(header + "\n")
    for data in array:
        file.write("\t".join(data)+"\n")

with open(file_name,'r',encoding="utf-8") as file:
    data = file.read()
    print(data)

순위	팀	승	무	패	승률
1	KIA	87	55	2	0.613
2	삼성	78	64	2	0.549
3	LG	76	66	2	0.535
4	두산	74	68	2	0.521
5	KT	72	70	2	0.507
6	SSG	72	70	2	0.507
7	롯데	66	74	4	0.471
8	한화	66	76	2	0.465
9	NC	61	81	2	0.430
10	키움	58	86	0	0.403



In [2]:
import pandas as pd
# 데이터 프레임
data = {
    'Name': ['홍길동', '임꺽정', '성춘향'],
    'Age': [25, 30, 27],
    'City': ['서울', '부산', '인천']
}
df = pd.DataFrame(data)
df


Name  Age City
0  홍길동   25   서울
1  임꺽정   30   부산
2  성춘향   27   인천

In [16]:

index = ['2020','2021','2022','2023','2024','2025']
yeonghee = pd.Series([140,150,160,170,180,190], index = index)
cheolsu = pd.Series([200,210,220,230,240,250], index = index)

result = pd.DataFrame({
    '영희' : yeonghee,
    '철수' : cheolsu
})

result


영희   철수
2020  140  200
2021  150  210
2022  160  220
2023  170  230
2024  180  240
2025  190  250

In [9]:
result.head() # 상위 5개만 가져옴
result.tail() # 하위

영희   철수
2021  150  210
2022  160  220
2023  170  230
2024  180  240
2025  190  250

In [15]:
#result.shape
result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 2020 to 2025
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   영희      6 non-null      int64  
 1   철수      5 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 144.0+ bytes


In [ ]:
# result.columns
# result.values
# result.index
# result.dtypes
# print(result['철수'])
# result[['철수']]


철수
2020  200
2021  210
2022  220
2023  230
2024  240
2025  250

In [ ]:
data = {
    'Name': ['홍길동', '임꺽정', '성춘향'],
    'Age': [25, 30, 27],
    'City': ['서울', '부산', '인천']
}
df = pd.DataFrame(data, index=['a','b','c'])
# df.loc['b']
# df.loc['b','Age']
# df.loc['a':'c','Name':'Age']
# df.loc[df['Age'] >= 30]
# df.loc[:, 'Name'] #( : , )전체라는 뜻
# df.loc['a', :]
# df.iloc[0]
# df.iloc[1,2]
# df.iloc[0:2, 0:2] # 끝값포함 안되
# df.iloc[[0,2], [1,2]]
# df.iloc[:, 0]
df.iloc[0, :]


Name    홍길동
Age      25
City     서울
Name: a, dtype: object

In [ ]:
data = {
    'Name': ['홍길동', '임꺽정', '성춘향'],
    'Age': [25, 30, 27],
    'City': ['서울', '부산', '인천']
}

df = pd.DataFrame(data)
print("기본 DataFrame:\n",df)

# 행 추가
new_data ={'Name': '이몽룡', 'Age':31,'City':'포함'}
result = pd.concat([df, pd.DataFrame([new_data]) ], ignore_index=True)
result

# 열 추가
result["직업"] = ["엔지니어","개발자","디자이너","기획자"]
result

# 값 수정
result.at[1,"City"] ="천안"
result.loc[result['Name'] == "임꺽정", "Age"] = 32
result

# 칼럼 이름 변경
result.rename(columns={'Name' : '이름','Age' : '나이'}, inplace=True)
result

# 데이터 정렬(내림차순)
result.sort_values(by='나이', inplace=True, ascending=False)
result

# 컬럼 삭제
result.drop(columns=['City'],inplace=True)
result



기본 DataFrame:
   Name  Age City
0  홍길동   25   서울
1  임꺽정   30   부산
2  성춘향   27   인천


이름  나이    직업
1  임꺽정  32   개발자
3  이몽룡  31   기획자
2  성춘향  27  디자이너
0  홍길동  25  엔지니어

In [82]:
# 실습2. 데이터프레임 만들기
data = {
    '이름':['홍길동','임꺽정','성춘향'],
    '수학':[85,90,78],
    '영어':[88,76,92],
    '과학':[95,89,84]
}

df = pd.DataFrame(data)
# new_data 추가
new_data={'이름':'이몽룡','수학':88,'영어':85,'과학':90}
df = pd.concat([df,pd.DataFrame([new_data])],ignore_index=True)
# 열 추가
df['Total'] = df['수학']+df['영어']+df['과학']
# df.at[1,'영어'] =80
df.loc[df['이름'] == '임꺽정','영어' ]=80
# 컬럼 이름 변경
df.rename(columns={'수학' : 'Math'}, inplace=True)

df


이름  Math  영어  과학  Total
0  홍길동    85  88  95    268
1  임꺽정    90  80  89    255
2  성춘향    78  92  84    254
3  이몽룡    88  85  90    263